# Generated by Django 6.0.2 on 2026-03-02 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Business Process',
                'verbose_name_plural': 'Business Processes',
            },
        ),
        migrations.CreateModel(
            name='SubProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('sequence_order', models.PositiveIntegerField(default=10, help_text='Controls position in workflow. Use multiples of 10 (10, 20, 30) to leave room for future insertions.')),
                ('is_primary_flow', models.BooleanField(default=True, help_text="Primary flow nodes appear in the connected linear workflow. Uncheck for standalone blocks like 'Vendor Rebates' or 'Intercompany'.")),
                ('business_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_processes', to='sox_controls.businessprocess')),
            ],
            options={
                'verbose_name': 'Sub Process',
                'verbose_name_plural': 'Sub Processes',
                'ordering': ['business_process', 'sequence_order'],
                'unique_together': {('business_process', 'sequence_order')},
            },
        ),
        migrations.CreateModel(
            name='SoxControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=50, unique=True)),
                ('control_description', models.TextField()),
                ('risk', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100)),
                ('effective_date', models.DateField()),
                ('sub_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='sox_controls.subprocess')),
            ],
            options={
                'verbose_name': 'SOX Control',
                'verbose_name_plural': 'SOX Controls',
            },
        ),
    ]
