# Generated by Django 6.0.2 on 2026-03-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sox_controls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soxcontrol',
            name='control_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
