# Generated by Django 6.0.2 on 2026-07-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sox_controls", "0003_businessprocess_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soxcontrol",
            name="risk",
            field=models.TextField(
                help_text="Describe what could go wrong if this control fails."
            ),
        ),
    ]
