# Generated by Django 6.0.7 on 2026-07-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sox_controls', '0004_alter_soxcontrol_risk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soxcontrol',
            options={'ordering': ['sub_process__business_process', 'sequence_order', 'id'], 'verbose_name': 'SOX Control', 'verbose_name_plural': 'SOX Controls'},
        ),
        migrations.AddField(
            model_name='soxcontrol',
            name='sequence_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for renumbering (lower numbers = earlier controls). Use multiples of 10 to allow insertions.'),
        ),
    ]
