# Generated by Django 6.0.7 on 2026-07-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sox_controls', '0005_alter_soxcontrol_options_soxcontrol_sequence_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soxcontrol',
            name='sequence_order',
            field=models.PositiveIntegerField(default=10, help_text='Order for renumbering (lower numbers = earlier controls). Use multiples of 10 to allow insertions.'),
        ),
    ]
