# Generated by Django 6.0.7 on 2026-07-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sox_controls', '0006_alter_soxcontrol_sequence_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soxcontrol',
            options={'ordering': ['sub_process__business_process', '-sequence_order', 'id'], 'verbose_name': 'SOX Control', 'verbose_name_plural': 'SOX Controls'},
        ),
    ]
