# Generated by Django 6.0.7 on 2026-07-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sox_controls', '0007_alter_soxcontrol_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soxcontrol',
            name='sequence_order',
            field=models.PositiveIntegerField(default=10, help_text='Order for renumbering (drag to reorder). Use multiples of 10 to allow insertions.'),
        ),
    ]
