# Generated by Django 6.0.7 on 2026-07-21 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sox_controls', '0008_alter_soxcontrol_sequence_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soxcontrol',
            options={'ordering': ['-sequence_order'], 'verbose_name': 'SOX Control', 'verbose_name_plural': 'SOX Controls'},
        ),
    ]
