# Generated by Django 6.0.7 on 2026-07-21 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sox_controls', '0009_alter_soxcontrol_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subprocess',
            options={'ordering': ['-sequence_order'], 'verbose_name': 'Sub Process', 'verbose_name_plural': 'Sub Processes'},
        ),
    ]
