# Generated by Django 6.0.7 on 2026-07-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sox_controls', '0010_alter_subprocess_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soxcontrol',
            options={'ordering': ['sequence_order'], 'verbose_name': 'Sub Process', 'verbose_name_plural': 'Sub Processes'},
        ),
    ]
