# Generated by Django 6.0.7 on 2026-07-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sox_controls', '0011_alter_soxcontrol_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soxcontrol',
            options={'ordering': ['-sequence_order'], 'verbose_name': 'SOX Control', 'verbose_name_plural': 'SOX Controls'},
        ),
        migrations.AlterUniqueTogether(
            name='subprocess',
            unique_together=set(),
        ),
    ]
