# Generated by Django 6.0.7 on 2026-07-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sox_controls', '0014_alter_soxcontrol_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='soxcontrol',
            name='control_type',
            field=models.CharField(choices=[('preventative', 'Preventative'), ('detective', 'Detective')], default='preventative', help_text='Preventative (prevents errors) or Detective (detects errors)', max_length=20),
        ),
        migrations.AddField(
            model_name='soxcontrol',
            name='execution_type',
            field=models.CharField(choices=[('automated', 'Automated'), ('manual', 'Manual')], default='automated', help_text='Automated (performed by system) or Manual (performed by person)', max_length=20),
        ),
        migrations.AddField(
            model_name='soxcontrol',
            name='implementation_details',
            field=models.TextField(blank=True, help_text='How the control is implemented in the system/process'),
        ),
        migrations.AddField(
            model_name='soxcontrol',
            name='test_procedures',
            field=models.TextField(blank=True, help_text='How to test that the control is working effectively'),
        ),
    ]
