# Generated by Django 6.1 on 2026-08-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sox_controls",
            "0015_soxcontrol_control_type_soxcontrol_execution_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="soxcontrol",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Concise, keyword-forward phrase for page titles/SEO (e.g. 'Vendor Master Data Dual Control'). Falls back to control_description if blank.",
                max_length=60,
            ),
        ),
    ]
