# Generated by Django 6.1 on 2026-08-18 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sox_controls", "0016_soxcontrol_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessNarrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Short summary shown in listings."
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Process narrative content in Markdown."
                    ),
                ),
                (
                    "disclaimer",
                    models.TextField(
                        default="This process narrative is provided as a generic reference describing a typical SAP S/4HANA process flow. Actual business processes, transaction codes, Fiori apps, and control configurations may differ based on your organization's specific SAP implementation, release, cloud/on-premise deployment, and industry configuration. Please validate against your own SAP system and control documentation.",
                        help_text="Caveat displayed at the top of the narrative.",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business_process",
                    models.OneToOneField(
                        help_text="The business process this narrative describes.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narrative",
                        to="sox_controls.businessprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Narrative",
                "verbose_name_plural": "Process Narratives",
                "ordering": ["business_process__name"],
            },
        ),
    ]
