# Generated by Django 6.0.7 on 2026-07-27 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITGCCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('sequence_order', models.PositiveIntegerField(default=10, help_text='Controls position in workflow. Use multiples of 10 (10, 20, 30) to leave room for future insertions.')),
                ('is_primary_flow', models.BooleanField(default=True, help_text='Primary flow nodes appear in the connected linear workflow. Uncheck for standalone blocks.')),
            ],
            options={
                'verbose_name': 'ITGC Category',
                'verbose_name_plural': 'ITGC Categories',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='ITGCLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(help_text="Short code for Control IDs (e.g. 'APP', 'DB', 'OS'). Cannot be changed once controls have been created.", max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ITGC Layer',
                'verbose_name_plural': 'ITGC Layers',
            },
        ),
        migrations.CreateModel(
            name='ITGCControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('control_description', models.TextField()),
                ('risk', models.TextField(help_text='Describe what could go wrong if this control fails.')),
                ('control_type', models.CharField(choices=[('preventative', 'Preventative'), ('detective', 'Detective')], default='preventative', help_text='Preventative (prevents errors) or Detective (detects errors)', max_length=20)),
                ('execution_type', models.CharField(choices=[('automated', 'Automated'), ('manual', 'Manual')], default='automated', help_text='Automated (performed by system) or Manual (performed by person)', max_length=20)),
                ('implementation_details', models.TextField(blank=True, help_text='How the control is implemented')),
                ('test_procedures', models.TextField(blank=True, help_text='How to test that the control is working effectively')),
                ('effective_date', models.DateField()),
                ('sequence_order', models.PositiveIntegerField(default=10, help_text='Order for renumbering. Use multiples of 10 to allow insertions.')),
                ('itgc_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='itgc.itgccategory')),
            ],
            options={
                'verbose_name': 'ITGC Control',
                'verbose_name_plural': 'ITGC Controls',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.AddField(
            model_name='itgccategory',
            name='itgc_layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='itgc.itgclayer'),
        ),
    ]
