# Generated by Django 6.1 on 2026-08-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itgc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itgccontrol",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Concise, keyword-forward phrase for page titles/SEO (e.g. 'Password Management'). Falls back to control_description if blank.",
                max_length=60,
            ),
        ),
    ]
