# Generated by Django 6.1 on 2026-08-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itgc", "0002_itgccontrol_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItgcNarrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "disclaimer",
                    models.TextField(
                        blank=True,
                        default="This narrative is a generic baseline. It is not specific to any company or SAP implementation and should be tailored to your environment.",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Markdown-formatted narrative content."),
                ),
                ("content_html", models.TextField(blank=True, editable=False)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        help_text="Select all ITGC categories that belong to this domain (e.g. Access Management categories across Application, Database, OS, and Network layers).",
                        related_name="narratives",
                        to="itgc.itgccategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "ITGC Narrative",
                "verbose_name_plural": "ITGC Narratives",
                "ordering": ["title"],
            },
        ),
    ]
