# Generated by Django 6.0.2 on 2026-02-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entryproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryproposal',
            name='send_rejection_email',
            field=models.BooleanField(default=False),
        ),
    ]
