name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - run: pip install -r requirements.txt
      
      - env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python manage.py test sox_controls itgc --keepdb
